project:
  type: website
  output-dir: docs
  # render:
    # - "*.qmd"
    # - "!templates/"
    # - "!data/"

website:
  favicon: images/favicon.png
  navbar:
    title: "EDS 223"
    right:
      - href: index.qmd
        text: home
      - text: syllabus
        href: https://docs.google.com/document/d/1uEfXTgl5TAkB50B46yjDWe_gEkgBNy38ghjwXqk40bs/view
        target: _blank
      - text: course materials
        menu: 
          - text: week 0
            href: course-materials/week0.qmd
          - text: week 1
            href: course-materials/week1.qmd
          
      - text: assignments
        href: assignments.qmd
      - text: redeem tokens
        href: https://script.google.com/a/macros/ucsb.edu/s/AKfycbx2l5pbXt0J8y2PnNi9Ohi3jxRZGd4dZfZMBMT_MWA23OPQ0Dt31vC7zbAWVHtcFC5C/exec
      - text: resources
        href: resources.qmd
      - icon: github
        href: https://github.com/EDS-223-Geospatial
        target: _blank
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/samanthacsik/EDS-212-essential-math), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html) and [Quarto](https://quarto.org/)
    left: |
      <img src="images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>


format:
  html:
    theme: meds-website-styles.scss
    toc: true
    title-block-banner: true
    page-layout: full
    callout-icon: false
    include-after-body: 
      text: |
        <script>
        document.addEventListener('DOMContentLoaded', function() {
          // Reinitialize Bootstrap dropdowns on every page load
          var dropdownElementList = [].slice.call(document.querySelectorAll('.dropdown-toggle'));
          dropdownElementList.forEach(function(dropdownToggle) {
            new bootstrap.Dropdown(dropdownToggle);
          });
        });
        </script>

editor: source



