---
title: "Homework Assignment 1"
subtitle: "Map making practice"
author: "Ruth Oliver"
date: last-modified
execute: 
  eval: false
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

:::{.callout-important icon=true}

You must earn a "Satisfactory" on **all** parts of the assignment to earn a "Satisfactory" on the assignment.

The assignment **must be submitted through Gradescope**. 

**Read each part of the assignment carefully**, and use the check boxes to ensure you've addressed all elements of the assignment!

:::

## Learning outcomes

- build effective, responsible, accessible and aesthetically-pleasing maps
- practice manipulating vector and raster data to build multi-layer maps
- practice making maps in R, specifically using `tmap`

## Instructions

1. Clone repository from GitHub Classrooms
2. Download data from [here](https://drive.google.com/file/d/1nG6Nj1bXfzQFOVMO8Km3eNy4SWu1YcIQ/view?usp=sharing)
3. Unzip data and place in repository
4. Edit Quarto document with responses
5. Push final edits before deadline

Your repository should have the following structure:

```{md}
EDS223-HW1
│   README.md
│   HW1.qmd
│   Rmd/Proj files    
│
└───data
     └───easter-island
     └───ejscreen
```







## Exploring environmental (in)justice

As many of us are aware, environmental degradation, pollution, and hazards is not felt equally by all people. Environmental justice has many definitions, but the United States Environmental Protection Agency defines it as follows:

>“Environmental justice” means the just treatment and meaningful involvement of all people, regardless of income, race, color, national origin, Tribal affiliation, or disability, in agency decision-making and other Federal activities that affect human health and the environment so that people:
>
> - are fully protected from disproportionate and adverse human health and environmental effects (including risks) and hazards, including those related to climate change, the cumulative impacts of environmental and other burdens, and the legacy of racism or other structural or systemic barriers; and
> - have equitable access to a healthy, sustainable, and resilient environment in which to live, play, work, learn, grow, worship, and engage in cultural and subsistence practices

For far too long, environmental inequities have been invisible, and thus ignored. Mapping environmental inequities can be a powerful tool for revealing injustices. We will be working with data from the United States Environmental Protection Agency's [EJScreen: Environmental Justice Screening and Mapping Tool](https://www.epa.gov/ejscreen).

According to the [US EPA website](https://www.epa.gov/ejscreen/purposes-and-uses-ejscreen):

>This screening tool and data may be of interest to community residents or other stakeholders as they search for environmental or demographic information. It can also support a wide range of research and policy goals. The public has used EJScreen in many different locations and in many different ways.
>
>EPA is sharing EJScreen with the public:
>
> - to be more transparent about how we consider environmental justice in our work,  
> - to assist our stakeholders in making informed decisions about pursuing environmental justice and,   
> - to create a common starting point between the agency and the public when looking at issues related to environmental justice.

### Description

For this assignment, you will explore an environmental justice topic of your choosing. You should select a region, community, or environmental issue that matters to you.

You must complete the following:

- [ ] create two maps that communicate an environmental justice issue
- [ ] write a brief paragraph explaining what your maps communicate

### Data details

EJScreen provides on environmental and demographic information for the US at the Census [tract](https://en.wikipedia.org/wiki/Census_tract) and [block group](https://en.wikipedia.org/wiki/Census_block_group) levels. You will be working with data at the block group level that has been downloaded from the [EPA site](https://www.epa.gov/ejscreen/download-ejscreen-data). To understand the associated data columns, you will need to explore the following in the `data` folder:

- Technical documentation: `ejscreen-tech-doc-version-2-2.pdf`
- Column descriptions: `EJSCREEN_2023_BG_Columns.xlsx`

You should also explore the [limitations and caveats](https://www.epa.gov/ejscreen/limitations-and-caveats-using-ejscreen) of the data.

The following code provides examples for reading and manipulating the EJScreen data. You MUST update this code to suite your problem of interest.

```{r}
#| eval: false

library(tidyverse)
library(sf)
library(here)

# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

# filter to a state you are interested in
california <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "CA") 

# filter to a county you are interested in
santa_barbara <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Santa Barbara County"))

# find the average values for all variables within counties
california_counties <- aggregate(california, by = list(california$CNTY_NAME), FUN = mean)

```


## Rubric (specifications)

You must complete the following to receive a "Satisfactory" on the assignment:

- [ ] All maps must include the following elements:
  - an informative title
  - legends with legible titles, including units
  - indication of scale and orientation (i.e. graticules/gridlines or scale bar and compass)
  - color scales that are accessible (i.e. make intuitive sense) and appropriate to the data (i.e. discrete vs. continuous)
- [ ] EJScreen maps and text must communicate about an issue
  - it is not sufficient to make two unrelated maps
- [ ] The rendered Quarto doc must show all required elements in a professional style
  - see examples of professional and unprofessional output on the [Assignments](../assignments.qmd) page


