---
title: "Homework Assignment 2"
subtitle: "Exploring patterns of environmental justice"
author: "Ruth Oliver"
date: last-modified
execute: 
  eval: false
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

:::{.callout-important icon=true}

You must earn a "Satisfactory" on **all** parts of the assignment to earn a "Satisfactory" on the assignment.

The assignment **must be submitted through GitHub Classrooms**. Each student receives one "free pass" for not submitting assignments via specified channels, after which you will receive a "Not Yet" mark.

**Read each part of the assignment carefully**, and use the check boxes to ensure you've addressed all elements of the assignment!

:::

## Learning outcomes

- build effective, responsible, accessible and aesthetically-pleasing maps
- practice manipulating vector and raster data to build multi-layer maps
- practice making maps in R, specifically using `tmap`

## Instructions

1. Clone repository from GitHub Classrooms
2. Download data from [here](https://drive.google.com/file/d/1nG6Nj1bXfzQFOVMO8Km3eNy4SWu1YcIQ/view?usp=sharing)
3. Unzip data and place in repository
4. Edit Quarto document with responses
5. Push final edits before deadline

Your repository should have the following structure:

```{md}
EDS223-HW1
│   README.md
│   HW1.qmd
│   Rmd/Proj files    
│
└───data
     └───easter-island
     └───ejscreen
```

## Background

Present-day environmental justice may reflect legacies of injustice in the past. The United States has a long history of racial segregation which is still visible. During the 1930's the Home Owners' Loan Corporation (HOLC), as part of the New Deal, rated neighborhoods based on their perceived safety for real estate investment. Their ranking system, (A (green), B (blue), C (yellow), D (red)) was then used to block access to loans for home ownership. Colloquially known as "redlining", this practice has had widely-documented consequences not only for community wealth, but also health.^[Gee, G. C. (2008). A multilevel analysis of the relationship between institutional and individual racial discrimination and health status. American journal of public health, 98(Supplement_1), S48-S56.] Redlined neighborhoods have less greenery^[Nardone, A., Rudolph, K. E., Morello-Frosch, R., & Casey, J. A. (2021). Redlines and greenspace: the relationship between historical redlining and 2010 greenspace across the United States. Environmental health perspectives, 129(1), 017006.] and are hotter than other neighborhoods.^[Hoffman, J. S., Shandas, V., & Pendleton, N. (2020). The effects of historical housing policies on resident exposure to intra-urban heat: a study of 108 US urban areas. Climate, 8(1), 12.] 

Check out coverage by the [New York Times](https://www.nytimes.com/interactive/2020/08/24/climate/racism-redlining-cities-global-warming.html).

A recent study found that redlining has not only affected the environments communities are exposed to, it has also shaped our observations of biodiversity.^[Ellis-Soto, D., Chapman, M., & Locke, D. H. (2023). Historical redlining is associated with increasing geographical disparities in bird biodiversity sampling in the United States. Nature Human Behaviour, 1-9.] Community or citizen science, whereby individuals share observations of species, is generating an enormous volume of data. Ellis-Soto and co-authors found that redlined neighborhoods remain the most undersampled areas across 195 US cities. This gap is highly concerning, because conservation decisions are made based on these data.

Check out coverage by [EOS](https://eos.org/articles/bird-biodiversity-reports-reflect-cities-redlined-past?utm_source=EosBuzz&mkt_tok=OTg3LUlHVC01NzIAAAGOx3ckQPpeDY3QyFKdUnBSYqILj3qLrgb_Q2lasphwcF90xEzMgjZFUo3NHsw3caXDcZe6I8D8qdVsSRr3wzhb6LKAQRgNo8ffhjieEbDwMw).


## Data details
### EJScreen
We will be working with data from the United States Environmental Protection Agency's EJScreen: Environmental Justice Screening and Mapping Tool.

According to the [US EPA website](https://www.epa.gov/ejscreen/purposes-and-uses-ejscreen):

>This screening tool and data may be of interest to community residents or other stakeholders as they search for environmental or demographic information. It can also support a wide range of research and policy goals. The public has used EJScreen in many different locations and in many different ways.
>
>EPA is sharing EJScreen with the public:  
> - to be more transparent about how we consider environmental justice in our work,  
> - to assist our stakeholders in making informed decisions about pursuing environmental justice and,   
> - to create a common starting point between the agency and the public when looking at issues related to environmental justice. 

EJScreen provides on environmental and demographic information for the US at the Census [tract](https://en.wikipedia.org/wiki/Census_tract) and [block group](https://en.wikipedia.org/wiki/Census_block_group) levels. You will be working with data at the block group level that has been downloaded from the [EPA site](https://www.epa.gov/ejscreen/download-ejscreen-data). To understand the associated data columns, you will need to explore the following in the `data` folder:

- Technical documentation: `ejscreen-tech-doc-version-2-2.pdf`
- Column descriptions: `EJSCREEN_2023_BG_Columns.xlsx`

You should also explore the [limitations and caveats](https://www.epa.gov/ejscreen/limitations-and-caveats-using-ejscreen) of the data.

### HOLC Redlining
A team of researchers, led by the [Digital Scholarship Lab](https://dsl.richmond.edu/) at the University of Richmond have digitized maps and information from the HOLC as part of the [Mapping Inequality](https://dsl.richmond.edu/panorama/redlining/#loc=5/39.1/-94.58) project. 

We will be working with maps of HOLC grade designations for Los Angeles. Information on the data can be found [here](https://dsl.richmond.edu/panorama/redlining/#loc=5/39.1/-94.58&text=downloads).^[Robert K. Nelson, LaDale Winling, Richard Marciano, Nathan Connolly, et al., “Mapping Inequality,” American Panorama, ed. Robert K. Nelson and Edward L. Ayers, accessed October 17, 2023, https://dsl.richmond.edu/panorama/redlining/] 

### Biodiversity observations
The [Global Biodiversity Information Facility](gbif.org) is the largest aggregator of biodiversity observations in the world. Observations typically include a location and date that a species was observed.

We will be working observations of birds from 2021 onward.


## Part 1: Legacy of redlining in current environmental (in)justice

Your first task is to explore historical redlining in Los Angeles and its legacy on present-day environmental justice.

### Description

For this assignment, you must produce the following:

- [ ] a map of historical redlining neighborhoods, including:
  - [ ] neighborhoods colored by HOLC grade
  - [ ] an appropriate base map
- [ ] a table summarizing the percent of current census block groups within each HOLC grade (or none)
- [ ] a set of figures summarizing current conditions (from the EJScreen data) within HOLC grades using the mean of the following variables:
  - [ ] % low income
  - [ ] percentile for Particulate Matter 2.5
  - [ ] percentile for low life expectancy
- [ ] a brief paragraph reflecting on these results


## Part 2: Legacy of redlining in biodiversity observations

Your second task is to explore the legacy of historical redlining in Los Angeles on the collection of bird observations.

### Description

For this assignment, you must produce the following based on observations from 2022:

- [ ] a figure summarizing the percent of observations within redlined neighborhoods within each HOLC grade
- [ ] a brief paragraph explaining whether these results match the findings from Ellis-Soto et al. 2023

## Rubric (specifications)

You must complete the following to receive a "Satisfactory" on the assignment:

- [ ] All maps must include the following elements:
  - an informative title
  - legends with legible titles, including units
  - indication of scale and orientation (i.e. graticules/gridlines or scale bar and compass)
  - color scales that are accessible (i.e. make intuitive sense) and appropriate to the data (i.e. discrete vs. continuous)
- [ ] All tables must:
  - must use professional-style formatting from `kable`
- [ ] The rendered Quarto doc must show all required elements in a professional style with explanation of each step of analysis
  - see examples of professional and unprofessional output on the [Assignments](../assignments.qmd) page




