---
title: "Geospatial Analysis blog post"
description: "Creating a blog post for your personal website"
author: "Ruth Oliver"
date: last-modified
execute: 
  eval: false
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---


## Assignment overview

The purpose of this assignment is to create a blogpost on your personal website that showcases your spatial data science skills.

To do so, please:

- Create a blog post based on Assignment 3 or 4. 

:::{.callout-tip icon=true}
# Tip

Pick the assignment that highlight the skills you are most interested in showcasing to potential employers.
:::

## Guidance for creating your blog post

The goal of creating a blog post is practice communicating your work in a different format. The audience of a blog post is more general than that of the repository, therefore you may be more selective in which code and output you display. In this case you are building a narrative around your work as opposed to demonstrating how it works, so you may want to only display intermediate and final results as opposed to results of self-checks and not output code. 



**The original assignment is a starting place.** You should use the background provided in the assignment as a starting place, but update the text and provide additional information and at least one additional reference.

## Blog Post Requirements {#requirements-section}
    
The style is up to you, but it should incorporate the following elements clearly:

- [ ] A problem statement or question that your analysis will address
- [ ] Background on why this issue is important (involving an additional reference)
- [ ] Explanation of the data sources, analyses, and results
- [ ] Clear, consistently formatted figures
      - I.e. informative axis labels/legends, visually appealing and consistent colors and          fonts
- [ ] Discussion of conclusions, including any potential caveats or future directions
- [ ] Posted on your personal website
    - [Resource on how to post a blog to your website by Sam Shanny Csik](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/)
    - Check out [this example](https://palomacartwright.github.io/posts/2021-11-24-hurricanes-and-gdp-growth-in-the-bahamas/) from a MEDS alumn
    
## Submitting assignment

Once you have completed your blog post, submit the following: 

- Submit the link to your blog post on your personal website on this [google form](https://forms.gle/rpkAf1JRh4oCoqRF7). 
- Save your blog post as a PDF and submit to the `Final Project Blog Post` portal on Gradescope. 


| Task                           | Due Date |
|:-------------------------------|:--------:|
| Blog post submission           | 12/06    |
| Blog post feedback released    | 12/10    |
| Blog post resubmission         | 12/12   |


 **Both a submission and a revised submission addressing all the feedback from the first revision will be needed to receive a Satisfactory.** An assignment without a resubmission will not get a *Satisfactory*, resulting in the highest possible letter grade for the course being a C. 

  
## Rubric

To receive a "Satisfactory", the blog post must include the elements described above in the [Blogpost Requirements](#requirements-section) section.



