---
title: "Final Self Reflection (SR #3)"
description: "Adapted from [An Bui's](https://an-bui.com/) reflection exercises in ENVS 193DS and Sam Csik's in [EDS 240](https://samanthacsik.github.io/EDS-240-data-viz/)"
author: "Ruth Oliver"
date: last-modified
execute: 
  eval: false
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

## Description

In this assignment you'll reflect on your learning through the course. Reread your response to the Pre-Course Self Reflection (SR #1) and Mid-Course Self Reflection (SR #2) and answer the following questions:

### Learning goals and plan
- [ ] Since SR #2, have you improved any of your existing skills or learned new ones?
- [ ] Have you accomplished the learning goals you outlined for this course in SR #1 (and potentially expanded on SR #2)? If you did, how did you do it? If you didn't why do you think you didn't?
- [ ] Did you learn new strategies for being accomplishing your goals? Will you revise your plan for future quarters?
- [ ] What are you proudest of accomplishing in this course?


### Course topics and structure
- [ ] What are some transferable skills that you developed in this course? How might you apply them to other courses or deliverables in your degree or to jobs in the future?
- [ ] What is one thing you really liked about this course, and why? What is one thing you think could be improved about this course, and how?
- [ ] Is there anything else you'd like the instructors to know about your experience in this course?


## Rubric (specifications)
To receive a "Satisfactory" score, you must adhere to the following:

- [ ] Submit your response [here](https://forms.gle/hogxVx7bmLgDrd3L9) by 11:59 PM on the due date. Extensions can be requested by [redeeming tokens](https://forms.gle/kSx5Fh9ve98U1tQA9).
- [ ] Your response must include answers to each question listed in the Description section.
- [ ] You should aim to answer each question in 2-4 sentences.
- [ ] Your responses must demonstrate genuine reflection. Obviously low effort responses will receive a "Not Yet". 

:::{.callout-tip icon=true}
## Tips for a "Satisfactory"

By clicking the boxes above, you can keep track of which items you've completed! I suggest drafting your response in a word document before copy/pasting into the submission form.

:::



