---
title: "Week 7: Remote Sensing Data"
subtitle: "EDS 223: Geospatial Analysis & Remote Sensing"
---

::: {.callout-tip}
## Reminder
[Check-in Quiz 2](https://forms.gle/ktXcVswidWv8Zxvc8) due Weekday, **DD-MM-YYYY** at HH:MM AM/PM.
:::

::: {.callout-tip}
## Reminder
Assignment 3 due Weekday, **DD-MM-YYYY** at HH:MM AM/PM.
:::

## Class Materials

| {{< fa calendar-day title="A calendary with one day highlighted" >}} Session  | {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} Topic  |  {{< fa laptop-code title="A laptop with on-screen code" >}} Lab |
|-------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------|
| Lecture  | [Data collection and processing with remote sensing data ](https://docs.google.com/presentation/d/1WPl_WN0_JqjscQIfsiKkYKLqispPcWEJqOdf1gFbPuA/present?usp=sharing){target="_blank"} | [Template](templates/week4.qmd) <br> [Answer key](labs/week4.html) |
| Discussion | TBD | [Template](templates/week7-discussion.qmd) <br> [Answer key](discussions/week7-discussion.html) |
: {.hover .bordered tbl-colwidths="[20,40,40]"} 

## Background Reading
- [Remote Sensing of the Environment, Chapter 1](/readings/Jensen-chapter1.pdf){target="_blank"}
- [Remote Sensing of the Environment, Chapter 2](/readings/Jensen-chapter2.pdf){target="_blank"}
- [How to Interpret a False-Color Satellite Image](https://earthobservatory.nasa.gov/features/FalseColor){target="_blank"}

## Technical Background
- [How raster functions map to stars functions](https://github.com/r-spatial/stars/wiki/How-%60raster%60-functions-map-to-%60stars%60-functions){target="_blank"}
- [Spatiotemporal raster data handling with stars](https://tmieno2.github.io/R-as-GIS-for-Economists/stars-basics.html#stars-basics){target="_blank"}
- [A comparison of terra and stars packages](https://www.r-bloggers.com/2021/05/a-comparison-of-terra-and-stars-packages/#:~:text=stars%20is%20set%2Dup%20to,stars%20can%20handle%20rotated%20grids.){target="_blank"}