---
title: "Spatial and geometry operations with vector data"
subtitle: "Week 3"
---

## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Class Materials

| Session                                                                         | Materials                                             |
|---------------------------------------------------------------------------------|-------------------------------------------------------|
| {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} Lecture | [Intro to basic spatial data and geometry operations with vector data](https://docs.google.com/presentation/d/1H0kwdJ3rzF6pJkgLYC5KzmMBmYzBV-NJRb1I-3zePYg/present?usp=sharing){target="_blank"}                  |
| {{< fa laptop-code title="A laptop with on-screen code" >}} Lab                 | [Spatial joins, topological relationships, and distance relationships](labs/week3.qmd){target="_blank"}        |
| {{< fa comments title="two speech bubbles" >}} Discussion               | [Practice with vector operations](discussions/week#.qmd){target="_blank"} |

## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}
| Assignment Type | Assignment Title                                                       |  Date Assigned | Date Due                   |
|:---------------:|------------------------------------------------------------------------|----------------|----------------------------|
| EOC             | [End-of-class survey (week 1)](https://forms.gle/aPGfCircFN1AZfSe9){target="_blank"}    | Mon 01/08/2024 | Mon 01/08/2024, 11:55pm PT |
| SR              | [Self reflection (SR #1)](../assignments/SR1-precourse.qmd){target="_blank"}      | Mon 01/08/2024 | Sat 01/13/2024, 11:59pm PT |
| HW              | [Homework Assignment #1](../assignments/HW1.qmd){target="_blank"}                       | Mon 01/08/2024 | Sat 01/20/2024, 11:59pm PT |


## Background Reading
- [Geocomputation with R, Chapter 4](https://r.geocompx.org/spatial-operations.html){target="_blank"}
- [Geocomputation with R, Chapter 5](https://r.geocompx.org/geometry-operations.html){target="_blank"}
- [GIS Fundamentals, Chapter 9 Part 1](readings/Bolstad-chapter9-part1.pdf){target="_blank"}
- [Douglas–Peucker Algorithm](https://cartography-playground.gitlab.io/playgrounds/douglas-peucker-algorithm/){target="_blank"} (Cartography Playground)
- [Line Simplification with Visvalingam–Whyatt Algorithm](https://bost.ocks.org/mike/simplify/){target="_blank"} (Mike Bostok)

## Technical Background
- [sf overview](https://r-spatial.github.io/sf/index.html){target="_blank"}
- [sf cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/sf.pdf){target="_blank"}
- [Introduction to sf and stars](https://r-spatial.org/book/07-Introsf.html){target="_blank"}