---
title: "Intro to spatial data models"
subtitle: "Week 2"
---


## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Class Materials

| Session                                                                         | Materials                                             |
|---------------------------------------------------------------------------------|-------------------------------------------------------|
| {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} Lecture | [Intro to spatial/vector data models](https://docs.google.com/presentation/d/1ywgmLUhRjI1uO5Ln2LgZ9lvG1KvZtvt1Zh_YQRz2kCs/present?usp=sharing){target="_blank"}                  |
| {{< fa laptop-code title="A laptop with on-screen code" >}} Lab                 | [Spatial operations with vector data](labs/week2.qmd){target="_blank"}        |
| {{< fa comments title="two speech bubbles" >}} Discussion               | [Working with multiple vector types](discussions/week2.qmd){target="_blank"} |

## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}
| Assignment Type | Assignment Title                                                       |  Date Assigned | Date Due                   |
|:---------------:|------------------------------------------------------------------------|----------------|----------------------------|
| EOC             | [End-of-class survey (week 1)](https://forms.gle/aPGfCircFN1AZfSe9){target="_blank"}    | Mon 01/08/2024 | Mon 01/08/2024, 11:55pm PT |
| SR              | [Pre-course reflection (SR #1)](../assignments/SR1-precourse.qmd){target="_blank"}      | Mon 01/08/2024 | Sat 01/13/2024, 11:59pm PT |
| HW              | [Homework Assignment #1](../assignments/HW1.qmd){target="_blank"}                       | Mon 01/08/2024 | Sat 01/20/2024, 11:59pm PT |

## {{< fa clipboard-list title="a clipboard with a To Do list" >}} Background Reading
- [*GIS Fundamentals*, Chapter 2 Part 2](readings/Bolstad-chapter2-part2.pdf){target="_blank"}
- [*Geocomputation with R*, Chapter 2](https://r.geocompx.org/spatial-class.html){target="_blank"}
- [*Geocomputation with R*, Chapter 3](https://r.geocompx.org/attr.html){target="_blank"}
- [*Geocomputation with R*, Chapter 7](https://r.geocompx.org/reproj-geo-data){target="_blank"}

## {{< fa clipboard-list title="a clipboard with a To Do list" >}} Additional Resources
- [sf overview](https://r-spatial.github.io/sf/index.html){target="_blank"}
- [sf cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/sf.pdf){target="_blank"}
- [Introduction to sf and stars](https://r-spatial.org/book/07-Introsf.html){target="_blank"}