---
title: "Week 5: Discussion Section - Answer Key"
subtitle: "Practice raster operations with vectors"
author: "Alessandra Vidal Meza"
date: last-modified
execute: 
  eval: true
format:
  html:
    toc: true
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(sf)
library(terra)
library(spData)
library(spDataLarge)
library(tidyverse)
```

```{r}
# load 30 random points from Zion National Park
zion_points <- read_sf(system.file("vector/zion_points.gpkg", package = "spDataLarge"))

# create a convex hull from the points 
zion_convex_hull <- sf::st_combine(zion_points) %>%
  sf::st_convex_hull() %>% 
  st_as_sf()

# load elevation raster data for Zion National Park, from the Shuttle Radar Topography Mission
srtm <- terra::rast(system.file("raster/srtm.tif", package = "spDataLarge"))

# load raster data representing grain sizes with the three classes clay, silt and sand
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```

## Crop and Mask `srtm`

```{r}
# crop 
srtm_crop1 <- crop(srtm, zion_points)
srtm_crop2 <- crop(srtm, zion_convex_hull)
plot(srtm_crop1, main = "Crop of srtm and zion_points")
plot(srtm_crop2, main = "Crop of srtm and zion_convex_hull")

srtm_mask1 <- mask(srtm, zion_points)
srtm_mask2 <- mask(srtm, zion_convex_hull)
plot(srtm_mask1, main = "Mask of srtm and zion_points")
plot(srtm_mask2, main = "Mask of srtm and zion_convex_hull")

srtm_inv_mask1 <- mask(srtm, zion_points, inverse = TRUE)
srtm_inv_mask2 <- mask(srtm, zion_convex_hull, inverse = TRUE)
plot(srtm_inv_mask1, main = "Inverse mask of srtm and zion_points")
plot(srtm_inv_mask2, main = "Inverse mask of srtm and zion_convex_hull")
```

## Subset Points in New Zealand/Aotearoa

```{r}
# subset New Zealand elevation points to > 3100 meters
nz_height3100 <- nz_height %>% 
  dplyr::filter(elevation > 3100)

# create template: define the extent, resolution, and CRS based on nz_height3100
nz_template <- rast(terra::ext(nz_height3100), 
                    resolution = 3000, 
                    crs = terra::crs(nz_height3100))
```

## Count Points in Each Grid Cell

```{r}
# convert vector points to raster data
# function "length" returns a count of the elevation points per cell
nz_raster <- rasterize(nz_height3100, nz_template, field = "elevation", fun = "length")

plot(nz_raster, main = "Number of Elevation Points > 3100 in Each Grid Cell")
plot(st_geometry(nz_height3100), add = TRUE)
```

## Find Maximum Elevation in Each Grid Cell

```{r}
# function "max" returns maximum elevation value per cell
nz_raster2 <- rasterize(nz_height3100, nz_template, field = "elevation", fun = max)

plot(nz_raster2, main = "Maximum Elevation in Each Grid Cell ")
plot(st_geometry(nz_height3100), add = TRUE)
```

## Aggregate and Resample Raster

```{r}
# reduce the resolution by combining 2 cells in each direction into larger cells
# sum the values of all cells for the resulting elevation value
nz_raster_low <- aggregate(nz_raster, fact = 2, fun = sum, na.rm = TRUE)

# convert the new raster's resolution back to the 3kmx3km resolution of original raster
nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 6 x 6 km", "Resample 6 x 6 km")
plot(plots, main = labs)
plot(nz_raster_low, main = "Resample 3 x 3 km")
```

## Vectorize Raster

```{r}
# convert raster data to polygon vector data
grain_poly <- as.polygons(grain) %>% 
  st_as_sf()

plot(grain, main = "Grain (Raster)")
plot(grain_poly, main = "Grain (Vector)")

# subset polygons to only clay
clay <- grain_poly %>% 
  dplyr::filter(grain == "clay")

plot(clay, main = "Clay")
```
